// <auto-generated />
using System;
using ISH_APP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISH_APP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501170452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISH_APP.Models.Assurance", b =>
                {
                    b.Property<int>("AssuranceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssuranceID"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Services")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssuranceID")
                        .HasName("PK__Assuranc__CB6737D6B5B8C069");

                    b.ToTable("Assurance");
                });

            modelBuilder.Entity("ISH_APP.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AssuranceID")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeAssurance")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientID")
                        .HasName("PK__Client__E67E1A04EAA5A29F");

                    b.HasIndex("AssuranceID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ISH_APP.Models.Dossier", b =>
                {
                    b.Property<int>("DossierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DossierID"));

                    b.Property<int?>("AssuranceID")
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireAssurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireISH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairePrestataire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateDebutTravaux")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDeclaration")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinTravaux")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PrestataireID")
                        .HasColumnType("int");

                    b.Property<string>("Priorite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeSinistre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DossierID")
                        .HasName("PK__Dossier__CABB1DF09F9A6B6B");

                    b.HasIndex("AssuranceID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PrestataireID");

                    b.ToTable("Dossier");
                });

            modelBuilder.Entity("ISH_APP.Models.Facture", b =>
                {
                    b.Property<int>("FactureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactureID"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateFacture")
                        .HasColumnType("date");

                    b.Property<int?>("DossierID")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontantHT")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MontantTTC")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MontantTVA")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FactureID")
                        .HasName("PK__Facture__511BBA009F004EFE");

                    b.HasIndex("DossierID");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("ISH_APP.Models.HistoriqueModification", b =>
                {
                    b.Property<int>("HistoriqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoriqueID"));

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampModifie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DossierID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoriqueID")
                        .HasName("PK__Historiq__0028F06DE7117746");

                    b.HasIndex("DossierID");

                    b.ToTable("HistoriqueModification");
                });

            modelBuilder.Entity("ISH_APP.Models.Modification", b =>
                {
                    b.Property<int>("ModificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModificationID"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DossierID")
                        .HasColumnType("int");

                    b.Property<string>("TypeModification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtilisateurID")
                        .HasColumnType("int");

                    b.HasKey("ModificationID")
                        .HasName("PK__Modifica__A3FE5A12EC0C9BEC");

                    b.HasIndex("DossierID");

                    b.HasIndex("UtilisateurID");

                    b.ToTable("Modification");
                });

            modelBuilder.Entity("ISH_APP.Models.Paiement", b =>
                {
                    b.Property<int>("PaiementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaiementID"));

                    b.Property<DateOnly?>("DatePaiement")
                        .HasColumnType("date");

                    b.Property<int?>("FactureID")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MontantRestant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Recu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PaiementID")
                        .HasName("PK__Paiement__A8FB0857BBD247F1");

                    b.HasIndex("FactureID");

                    b.ToTable("Paiement");
                });

            modelBuilder.Entity("ISH_APP.Models.PieceJointe", b =>
                {
                    b.Property<int>("PieceJointeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PieceJointeID"));

                    b.Property<string>("CheminFichier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DossierID")
                        .HasColumnType("int");

                    b.Property<string>("NomFichier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeFichier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PieceJointeID")
                        .HasName("PK__PieceJoi__27E19E15C63AFF3E");

                    b.HasIndex("DossierID");

                    b.ToTable("PieceJointe");
                });

            modelBuilder.Entity("ISH_APP.Models.Prestataire", b =>
                {
                    b.Property<int>("PrestataireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestataireID"));

                    b.Property<string>("AdresseSiege")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Agences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostalSiege")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Horaires")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Note")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Services")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TarifNormal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TarifSoirWeekendFerie")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("VilleSiege")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrestataireID")
                        .HasName("PK__Prestata__0CB38DF24A9706F3");

                    b.ToTable("Prestataire");
                });

            modelBuilder.Entity("ISH_APP.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotDePasseHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UtilisateurID")
                        .HasName("PK__Utilisat__6CB6AE1FE8FEDB5B");

                    b.HasIndex(new[] { "Email" }, "UQ__Utilisat__A9D10534CA3CCA1E")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("ISH_APP.Models.Client", b =>
                {
                    b.HasOne("ISH_APP.Models.Assurance", "Assurance")
                        .WithMany("Clients")
                        .HasForeignKey("AssuranceID")
                        .HasConstraintName("FK__Client__Assuranc__3E52440B");

                    b.Navigation("Assurance");
                });

            modelBuilder.Entity("ISH_APP.Models.Dossier", b =>
                {
                    b.HasOne("ISH_APP.Models.Assurance", "Assurance")
                        .WithMany("Dossiers")
                        .HasForeignKey("AssuranceID")
                        .HasConstraintName("FK__Dossier__Assuran__4222D4EF");

                    b.HasOne("ISH_APP.Models.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("ClientID")
                        .HasConstraintName("FK__Dossier__ClientI__412EB0B6");

                    b.HasOne("ISH_APP.Models.Prestataire", "Prestataire")
                        .WithMany("Dossiers")
                        .HasForeignKey("PrestataireID")
                        .HasConstraintName("FK__Dossier__Prestat__4316F928");

                    b.Navigation("Assurance");

                    b.Navigation("Client");

                    b.Navigation("Prestataire");
                });

            modelBuilder.Entity("ISH_APP.Models.Facture", b =>
                {
                    b.HasOne("ISH_APP.Models.Dossier", "Dossier")
                        .WithMany("Factures")
                        .HasForeignKey("DossierID")
                        .HasConstraintName("FK__Facture__Dossier__6EF57B66");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("ISH_APP.Models.HistoriqueModification", b =>
                {
                    b.HasOne("ISH_APP.Models.Dossier", "Dossier")
                        .WithMany("HistoriqueModifications")
                        .HasForeignKey("DossierID")
                        .HasConstraintName("FK__Historiqu__Dossi__49C3F6B7");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("ISH_APP.Models.Modification", b =>
                {
                    b.HasOne("ISH_APP.Models.Dossier", "Dossier")
                        .WithMany("Modifications")
                        .HasForeignKey("DossierID")
                        .HasConstraintName("FK__Modificat__Dossi__74AE54BC");

                    b.HasOne("ISH_APP.Models.Utilisateur", "Utilisateur")
                        .WithMany("Modifications")
                        .HasForeignKey("UtilisateurID")
                        .HasConstraintName("FK__Modificat__Utili__75A278F5");

                    b.Navigation("Dossier");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ISH_APP.Models.Paiement", b =>
                {
                    b.HasOne("ISH_APP.Models.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureID")
                        .HasConstraintName("FK__Paiement__Factur__71D1E811");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("ISH_APP.Models.PieceJointe", b =>
                {
                    b.HasOne("ISH_APP.Models.Dossier", "Dossier")
                        .WithMany("PieceJointes")
                        .HasForeignKey("DossierID")
                        .HasConstraintName("FK__PieceJoin__Dossi__45F365D3");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("ISH_APP.Models.Assurance", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("ISH_APP.Models.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("ISH_APP.Models.Dossier", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("HistoriqueModifications");

                    b.Navigation("Modifications");

                    b.Navigation("PieceJointes");
                });

            modelBuilder.Entity("ISH_APP.Models.Facture", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("ISH_APP.Models.Prestataire", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("ISH_APP.Models.Utilisateur", b =>
                {
                    b.Navigation("Modifications");
                });
#pragma warning restore 612, 618
        }
    }
}
